credentials:
  usernames:
    Pavan:
      email: pavankumar@gmail.com
      name: Pavan kumar varma
      password: $2b$12$G73ohixZz3xVmPVz3cEc9eKNTostfncK5zqzrJg.Q4niWo5RKZhMC
    Admin:
      email: admin@gmail.com
      name: Admin
      password: $2b$12$iUxK7gYUYbsM1pe7XPfrYO6ds4dwlWXtK8U7sTDDuPc9idSXS2qna
cookie:
  expiry_days: 30
  key: Admin # Must be string
  name: Admin
preauthorized:
  emails:
  - pavankumar@gmail.com